[theme]
primaryColor = "#5BAEDC"                # Azul Claro
backgroundColor = "#FFFFFF"             # Branco
secondaryBackgroundColor = "#F7F7F7"   # Cinza Claro
textColor = "#212529"                   # Preto Suave
font = "sans serif"                     # Fonte global

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
